module.exports = {
    extends: ["stylelint-config-standard"],
    plugins: ["stylelint-order", "stylelint-scss"],
    rules: {
        indentation: "tab",
        "max-nesting-depth": 5,
        "selector-max-compound-selectors": 5,
        "color-named": "always-where-possible",
        "at-rule-no-unknown": null,
        "string-quotes": "double",
        "declaration-empty-line-before": null,
        "property-no-vendor-prefix": true,
        "declaration-no-important": true,
        "selector-pseudo-class-no-unknown": [
            true,
            {
                ignorePseudoClasses: ["global"],
            },
        ],
        "scss/at-rule-no-unknown": [
            true,
            {
                ignoreAtRules: [
                    "tailwind",
                    "apply",
                    "variants",
                    "responsive",
                    "screen",
                    "layer",
                ],
            },
        ],
        "selector-class-pattern": "(^[a-z]|[a-zA-Z0-9])*|\\.(\\?|\\*|\\.)",
        "declaration-block-trailing-semicolon": null,
        "no-descending-specificity": null,
        "order/order": [
            "declarations",
            "custom-properties",
            "dollar-variables",
            "at-variables",
            "rules",
            "at-rules",
        ],
        "order/properties-order": [
            [
                {
                    groupName: "box Model & display",
                    emptyLineBefore: "always",
                    properties: [
                        "display",
                        "height",
                        "width",
                        "min-height",
                        "min-width",
                        "max-height",
                        "max-width",
                        "overflow",
                        "overflow-x",
                        "overflow-y",
                        "flex-direction",
                        "flex-wrap",
                        "flex",
                        "gap",
                        "flex-basis",
                        "flex-flow",
                        "flex-grow",
                        "flex-shrink",
                        "align-content",
                        "align-items",
                        "align-self",
                        "justify-content",
                        "place-content",
                        "order",
                        "grid",
                        "grid-area",
                        "grid-gap",
                        "grid-template",
                        "grid-template-areas",
                        "grid-template-rows",
                        "grid-template-columns",
                        "grid-row",
                        "grid-row-start",
                        "grid-row-end",
                        "grid-row-gap",
                        "grid-column",
                        "grid-column-start",
                        "grid-column-end",
                        "grid-column-gap",
                        "grid-auto-rows",
                        "grid-auto-columns",
                        "grid-auto-flow",
                        "grid-gap",
                        "grid-row-gap",
                        "grid-column-gap",
                        "opacity",
                    ],
                },
                {
                    groupName: "position",
                    emptyLineBefore: "always",
                    properties: [
                        "position",
                        "top",
                        "right",
                        "bottom",
                        "left",
                        "z-index",
                    ],
                },
                {
                    groupName: "transforms",
                    emptyLineBefore: "always",
                    properties: ["transform", "transform-origin"],
                },
                {
                    groupName: "spacings & borders",
                    emptyLineBefore: "always",
                    properties: [
                        "box-sizing",
                        "padding",
                        "padding-top",
                        "padding-right",
                        "padding-bottom",
                        "padding-left",
                        "margin",
                        "margin-top",
                        "margin-right",
                        "margin-bottom",
                        "margin-left",
                        "border",
                        "border-color",
                        "border-style",
                        "border-width",
                        "border-top",
                        "border-top-color",
                        "border-top-style",
                        "border-top-width",
                        "border-right",
                        "border-right-color",
                        "border-right-style",
                        "border-right-width",
                        "border-bottom",
                        "border-bottom-color",
                        "border-bottom-style",
                        "border-bottom-width",
                        "border-left",
                        "border-left-color",
                        "border-left-style",
                        "border-left-width",
                        "border-radius",
                        "border-top-left-radius",
                        "border-top-right-radius",
                        "border-bottom-right-radius",
                        "border-bottom-left-radius",
                        "border-image",
                        "border-image-source",
                        "border-image-slice",
                        "border-image-width",
                        "border-image-outset",
                        "border-image-repeat",
                        "outline",
                        "outline-width",
                        "outline-style",
                        "outline-color",
                        "outline-offset",
                        "box-shadow",
                        "mix-blend-mode",
                    ],
                },
                {
                    groupName: "background",
                    emptyLineBefore: "always",
                    properties: [
                        "background",
                        "background-color",
                        "background-image",
                        "background-repeat",
                        "background-position",
                        "background-attachment",
                        "background-clip",
                        "background-origin",
                        "background-size",
                    ],
                    order: "flexible",
                },
                {
                    groupName: "fonts",
                    emptyLineBefore: "always",
                    properties: [
                        "font-family",
                        "font-size",
                        "font-style",
                        "font-weight",
                        "line-height",
                        "color",
                        "text-transform",
                        "text-decoration",
                    ],
                },
                {
                    groupName: "interactivity",
                    emptyLineBefore: "always",
                    properties: ["user-select", "cursor"],
                },
                {
                    groupName: "animations",
                    emptyLineBefore: "always",
                    properties: [
                        "animation",
                        "animation-name",
                        "animation-duration",
                        "animation-timing-function",
                        "animation-delay",
                        "animation-iteration-count",
                        "animation-direction",
                        "animation-fill-mode",
                        "animation-play-state",
                        "transition",
                        "transition-property",
                        "transition-duration",
                        "transition-timing-function",
                        "transition-delay",
                    ],
                },
            ],
            {
                unspecified: "bottomAlphabetical",
                emptyLineBeforeUnspecified: "always",
            },
        ],
    },
};
